# Configuration for different property groups and their listings/rate mappings.
# Top-level 'properties' key: app uses config.get("properties", data) for compatibility.

properties:
  onera: # Combined Fredericksburg Basse 1 & 2 properties
    name: "Onera"
    pms: cloudbeds
    total_units: 38
    listings:
      - {name: "Cocoon", id: "203812___362535", batna: 189.00}
      - {name: "Walnut House", id: "203812___364773", batna: 209.00}
      - {name: "Spyglass", id: "203812___364776", batna: 209.00}
      - {name: "Live Oak Lodge", id: "203812___364778", batna: 209.00}
      - {name: "Lantana Dome", id: "203812___364779", batna: 189.00}
      - {name: "Sage Safari", id: "203812___364780", batna: 189.00}
      - {name: "Monarch", id: "203812___364781", batna: 209.00}
      - {name: "Buckeye Bungalow", id: "203812___364782", batna: 189.00}
      - {name: "Cedar Haus", id: "203812___490007", batna: 169.00}
      - {name: "Juniper Haus", id: "203812___490024", batna: 169.00}
      - {name: "Pecan Haus", id: "203812___528745", batna: 169.00}
      - {name: "Bluebonnet", id: "203812___634080", batna: 189.00}
      - {name: "Great Lodge", id: "203812___643757", units: 1, batna: 1352}
      - {name: "Great Lodge: King Room", id: "203812___643775", units: 6, batna: 169.00}
      - {name: "Great Lodge: King Room (Accessible)", id: "203812___657152", units: 2, batna: 169.00}
      - {name: "Cypress Lodge | Sleeps 2", id: "203812___655826", units: 2, batna: 169.00}
      - {name: "Cypress Lodge | Sleeps 4", id: "203812___643762", units: 2, batna: 229.00}
      - {name: "Cypress Lodge | Sleeps 6", id: "203812___655827", units: 2, batna: 229.00}
      - {name: "Diamond", id: "203812___643771", units: 3, batna: 229.00}
      - {name: "Monolith", id: "203812___643773", units: 2, batna: 229.00}
      - {name: "Post Oak", id: "203812___643760", units: 1, batna: 169.00}
      - {name: "Quonset", id: "203812___643764", units: 2, batna: 209.00}
      - {name: "Spiral", id: "203812___643772", units: 1, batna: 229.00}
      - {name: "Winecup", id: "203812___643766", units: 2, batna: 209.00}
    rate_group_mapping:
      rate_1: ["203812___364781", "203812___364776", "203812___364778", "203812___364773"]
      rate_2: ["203812___364780", "203812___362535", "203812___364782", "203812___364779", "203812___634080"]
      rate_3: ["203812___490007", "203812___490024", "203812___528745"]
      rate_4: ["203812___643772", "203812___643771"]
      rate_5: ["203812___643766", "203812___643764"]
      rate_6: ["203812___643757"]
      rate_7: ["203812___643775", "203812___657152"]
      rate_8: ["203812___643773"]
      rate_9: ["203812___655826", "203812___643762", "203812___655827"]
      rate_10: ["203812___643760"]

  wb1:
    name: "Onera Wimberley"
    pms: cloudbeds
    total_units: 28
    listings:
      - {name: "Greenhouse", id: "316005___633306", units: 9, batna: 169.00}
      - {name: "Greenhouse ADA", id: "316005___633307", units: 1, batna: 169.00}
      - {name: "Spyglass", id: "316005___633310", units: 5, batna: 189.00}
      - {name: "Spyglass ADA", id: "316005___633311", units: 1, batna: 189.00}
      - {name: "Greenhouse Pet", id: "316005___633308", units: 6, batna: 169.00}
      - {name: "Spyglass Pet", id: "316005___633312", units: 6, batna: 189.00}
    rate_group_mapping:
      rate_1: ["316005___633306", "316005___633307"]
      rate_2: ["316005___633308"]
      rate_3: ["316005___633310", "316005___633311"]
      rate_4: ["316005___633312"]

  pblu1:
    name: "ParcBlu"
    pms: hostaway
    listings:
      - {name: "Love", id: "299754", batna: 120.00}
      - {name: "Peace", id: "299755", batna: 120.00}
      - {name: "Joy", id: "299756", batna: 120.00}
      - {name: "Delight", id: "299757", batna: 140.00}
      - {name: "Grace", id: "299758", batna: 140.00}
      - {name: "Dream", id: "299759", batna: 120.00}
      - {name: "Beauty", id: "299760", batna: 140.00}
      - {name: "Unit #15 - Livin' the Dream -- Cozy Camper Retreat for Two", id: "465407", batna: 100.00}
      - {name: "Unit #11 - Favored -- Private Glass Cabin with Covered Porch and Hot Tub", id: "465408", batna: 200.00}
    rate_group_mapping:
      rate_1: ["299757", "299758", "299760"]
      rate_2: ["299754", "299755", "299756", "299759", "465407", "465408"]

  atx1:
    name: "Austin"
    pms: hostaway
    listings:
      - {name: "Romney", id: "320201", batna: 139.00}
      - {name: "Sunstrip", id: "320203", batna: 169.00}
      - {name: "Malvern", id: "389561", batna: 159.00}
    rate_group_mapping:
      rate_4: ["320203"]
      rate_2: ["389561"]
      rate_1: ["320201"]

  sos1:
    name: "Spirit of Sofia"
    pms: guesty
    total_units: 3
    listings:
      - {name: "12BR/Sleeps 30! Designer Poolside Adventure Dwtn!", id: "68642480da9649000fc63fc5", units: 1, batna: 750.00}
      - {name: "11BR Designer Villa! Poolside Dntwn PS! Sleeps 30", id: "686424c7c8d43b001321df29", units: 1, batna: 650.00}
      - {name: "23BR Designer Concept Buyout! True PS Experience!", id: "686424d94cdb20000e10b8db", units: 1, batna: 1500.00}
    rate_group_mapping:
      rate_1: ["686424d94cdb20000e10b8db"]
      rate_2: ["686424c7c8d43b001321df29", "68642480da9649000fc63fc5"]

  spm1:
    name: "Spoon Mountain"
    pms: ownerrez
    listings:
      - {name: "Chisum", id: "278915", batna: 189.00}
      - {name: "Kingfisher", id: "303587", batna: 189.00}
      - {name: "Shaka", id: "303588", batna: 189.00}
    rate_group_mapping:
      rate_1: ["278915", "303587", "303588"]

  flo1:
    name: "FLOHOM"
    pms: hostaway
    listings:
      - {name: "FLOHOM 1", id: "146908", batna: 275.00}
      - {name: "FLOHOM 2", id: "146944", batna: 225.00}
      - {name: "FLOHOM 3", id: "146946", batna: 125.00}
      - {name: "FLOHOM 4", id: "260001", batna: 275.00}
      - {name: "FLOHOM 5", id: "278502", batna: 200.00}
      - {name: "FLOHOM 6", id: "345316", batna: 300.00}
      - {name: "FLOHOM 7", id: "366176", batna: 250.00}
      - {name: "FLOHOM 8", id: "376368", batna: 175.00}
      - {name: "FLOHOM 9", id: "383097", batna: 200.00}
      - {name: "FLOHOM 10", id: "404358", batna: 250.00}
      - {name: "FLOHOM 11", id: "427313", batna: 125.00}
      - {name: "FLOHOM 12", id: "422608", batna: 250.00}
      - {name: "FLOHOM 14", id: "407612", batna: 150.00}
    rate_group_mapping:
      rate_1: ["146946"]
      rate_2: ["376368"]
      rate_3: ["278502", "383097", "404358", "407612", "422608", "427313"]
      rate_4: ["146944"]
      rate_5: ["366176", "345316"]
      rate_6: ["260001"]
      rate_7: ["146908"]

  melrose1:
    name: "Hotel Melrose"
    pms: cloudbeds
    listings:
      - {name: "Kannah Creek Suites (Single King)", id: "257940___534397", units: 3, batna: 150.00}
      - {name: "Ponsford Suite (Deluxe King)", id: "257940___537039", units: 7, batna: 165.00}
      - {name: "Cattlemans Twofold (Deluxe Double Queen)", id: "257940___537043", units: 3, batna: 165.00}
      - {name: "The London Double (Double Queen)", id: "257940___575558", units: 1, batna: 165.00}
      - {name: "1884 Quarters (Single Queen)", id: "257940___537037", units: 2, batna: 150.00}
    rate_group_mapping:
      rate_1: ["257940___534397", "257940___537039"]
      rate_2: ["257940___537043", "257940___575558"]
      rate_3: ["257940___537037"]

  azulik1:
    name: "Azulik"
    pms: cloudbeds
    total_units: 48
    listings:
      - {name: "AZULIK Jungle Villa", id: "283597___530612", units: 8, batna: 4638.00}
      - {name: "AZULIK Mayan Villa", id: "283597___530715", units: 12, batna: 5565.00}
      - {name: "AZULIK Aztec Villa", id: "283597___530718", units: 4, batna: 6122.00}
      - {name: "AZULIK Sea Villa", id: "283597___530720", units: 11, batna: 7420.00}
      - {name: "AZULIK Sky Villa", id: "283597___530761", units: 11, batna: 9275.00}
      - {name: "AZULIK Moon Villa", id: "283597___530766", units: 1, batna: 51940.00}
      - {name: "AZULIK Aqua Villa", id: "283597___530767", units: 1, batna: 40810.00}
    rate_group_mapping:
      rate_1: ["283597___530612", "283597___530718"]
      rate_2: ["283597___530715", "283597___530720", "283597___530761"]
      rate_3: ["283597___530766", "283597___530767"]

  mayamod1:
    name: "Maya & Mod"
    pms: guesty
    listings:
      - {name: "Maya -- Maya Hotel Retreat", id: "6901008185d27c0022d3ba14", batna: 549.00}
      - {name: "Mod -- The Mod Hotel", id: "6901037df868fc002a10e0d7", batna: 449.00}
      - {name: "M&M -- Maya & Mod Double Buyout", id: "6901051a7cc21d0029679ae6", batna: 976.00}
    rate_group_mapping:
      rate_1: ["6901008185d27c0022d3ba14"]
      rate_2: ["6901037df868fc002a10e0d7"]
      rate_3: ["6901051a7cc21d0029679ae6"]
